# Name Service
spring:
  application:
    name: retrieve-result-release-dates-service
  cloud:
    config:
      env: default # optional
      label: master # optional
      uri: ${CONFIG_SERVER:http://localhost:8888} # optional

      